# -*- coding: utf-8 -*-
"""bone_fracture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ojUtbWE3PaNHYWQ5UkKqH5Y4cLsdZBs
"""

!pip install ultralytics
!pip install opencv-python
!pip install matplotlib

from ultralytics import YOLO

# Load pretrained YOLO model
model = YOLO("yolo26x.pt")

model.train(
    data="/content/drive/MyDrive/Bone Fractures Detection/data.yaml",
    epochs=100,
    imgsz=640,
    batch=8,        # smaller batch to fit GPU memory
    device=0,
    augment=True
)

metrics = model.val()
print(metrics)

results = model("/content/drive/MyDrive/Bone Fractures Detection/test/images/101_jpg.rf.92e32f9dfb9b34f9a123b16629cc368d.jpg", show=True)
# Save prediction
results[0].save("output.jpg")